notifications:
  slack: openodeio:6BDG0odfHQqNmWXoYcDfpV2y

language: ruby

before_script:
  - sudo apt-get install -qq sshpass

script:
  - bundle exec rubocop
  #- RAILS_ENV=test bundle exec bin/rails webpacker:compile
  - bundle exec bin/rails test

deploy:
  provider: script
  script: env bash scripts/deploy.sh
  on:
    branch: master