notifications:
  slack: openodeio:6BDG0odfHQqNmWXoYcDfpV2y
language: ruby

before_install:
- nvm install 12

before_script:
- node -v

script:
- RAILS_ENV=test NODE_ENV=test bundle exec bin/rails webpacker:compile
- bundle exec rubocop
- bundle exec bin/rails test
deploy:
  provider: script
  script: env bash scripts/deploy.sh
  on:
    branch: master
