notifications:
  slack: openodeio:6BDG0odfHQqNmWXoYcDfpV2y
language: ruby

# before_script:
# - sudo apt-get install -qq xxxx

script:
- NODE_ENV=test bundle exec rails webpacker:compile
- bundle exec rubocop
- bundle exec bin/rails test
deploy:
  provider: script
  script: env bash scripts/deploy.sh
  on:
    branch: master
